implemented case competition page lol cool
InnoD-WebTier/irc_v2 pull request #9
Opened 2017-11-13 09:08 UTC by cindytung

2017-11-13 09:31 UTC, dav1dn requested changes

2017-11-13 09:31 UTC, emesde commented on src/layouts/index.jsx
> +        paddingTop: 21,
would prefer this to be in a .scss file -- conventionally, you'd make a `$navbar-height` variable in _mixins.scss and then use that everywhere else you need to pad for it

2017-11-13 09:31 UTC, emesde commented on src/styles/base.scss
> +  min-height: 100%
;

2017-11-13 09:31 UTC, emesde commented on src/pages/case-competition.jsx
> +            1st Annual IRC Case Competition
this is a page that should support multiple case competitions, right? you need to genericize case comp into components that can take arbitrary .md data to form each event, like a blog/list of events

2017-11-13 09:31 UTC, emesde commented on src/pages/case-competition.jsx
> +          <div className="section__header">
use more descriptive element names -- this is a CaseCompetition, not a section

2017-11-13 09:31 UTC, emesde commented on src/pages/case-competition.jsx
> +        <img id="city-scape-background" alt="" src={background} />
think i prefer this as a background-image, but this is also fine

2017-11-13 09:31 UTC, dav1dn commented on src/styles/base.scss
> +  .section__subline {
subtext?

2017-11-14 02:19 UTC, cindytung commented on src/styles/base.scss
> +  .section__subline {
english :~)

2017-11-16 07:54 UTC, merged